C Dianyun Zhang     
C dianyun.zhang@uconn.edu
C Last Debugged: 02/19/2018

C IF THE MATERIAL NAME = LAMINA, CALL THE HOMOGENIZED LAMINAR MODEL
C                                LINEAR ELASTIC UPTO FAILURE
C IF THE MATERIAL NAME = CARBON, CALL THE MICROMECHANICAL MODEL
C                                NONLINEAR DAMAGE AND FRACTURE MODEL 
C IF THE MATERIAL NAME = MATRIX, CALL MATRIX DAMAGE AND FRACTURE MODEL

      
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)

      INCLUDE 'ABA_PARAM.INC'

      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)


      DIMENSION EPS(6)
      
      EPS = STRAN+DSTRAN

      
      IF (CMNAME(1:2) .EQ. 'LA') THEN
         CALL SCA_LAMINA(NSTATV, NPROPS, NOEL, TIME(1), TIME(2),
     1     DTIME, CELENT, PROPS, EPS, STRESS, STATEV, DDSDDE, DTEMP,1)     
      END IF
      IF(CMNAME(1:2) .EQ. 'CA') THEN
         CALL CCM3D_ANISO(NSTATV, NPROPS, NOEL, TIME(1), TIME(2),
     1     DTIME, CELENT, PROPS, EPS, STRESS, STATEV, DDSDDE, 1,DSTRAN)

      ELSE IF(CMNAME(1:2) .EQ. 'MA') THEN
         CALL UMAT_MATRIX(NSTATV, NPROPS, NOEL, TIME(1), TIME(2),
     1     DTIME, CELENT, PROPS, EPS, STRESS, STATEV, DDSDDE, 1)   
      END IF


      RETURN
      END
      

      INCLUDE 'ccm3d_aniso.for'
      INCLUDE 'matrix_inverse.for'
      include 'myaux.for'
      include 'my_standard_support.for'
      INCLUDE 'subroutines_for_ccm3d_aniso.for'
      INCLUDE 'sca_aniso.for'
      INCLUDE 'sca_lamina.for'
      INCLUDE 'umat_matrix.for'
      INCLUDE 'sca3d_iso'
